### PR TITLE
Proper django management command

### PR DESCRIPTION
**Pull request by maccesch**

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
thats a good start, for more detailed handling support for collectstatic and stuff like the compressing pipelines might be usefull

**Comment by maccesch** [comment]
hm true. I used the `get_internal_wsgi_application()` method of the django dev server so staticfiles are working just out of the box like in `runserver`

The compressing pipeline is nice but I think most of the time django-compressor is the better choice since it's able to merge js files etc

**Comment by RonnyPfannschmidt** [comment]
if django-compressors already works, i think tis fine, i asnt talking about a specific tool, i jsut recalled thse can be problematic

**Comment by maccesch** [comment]
Ah I see. Well this is meant as a start and a small improvement over the manage.py hack :)

**Comment by lepture** [comment]
the package is not in setup.py yet

**Comment by maccesch** [comment]
It's inside the livereload package, which is already included. This way the Django user can simply include `'livereload'` in they `INSTALLED_APPS`.

**Comment by maccesch** [comment]
Sorry, didn't realize it before. It's added now to setup.py

**Comment by lepture** [comment]
sorry for the delay.

**Pull request merged**
