### PR TITLE
cache etag and mtime, recalc etag only on mtime change

### PR DESCRIPTION
**Pull request by andreycizov**
Solves #183 by checking file mtime on every request before returning cached etag.

### CODE REVIEW

**Comment by andreycizov** [comment]
Could we get a response on this one?

**Comment by lepture** [comment]
Thanks

**Comment by andreycizov** [comment]
Thanks to you!

**Comment by andreycizov** [comment]
Could you please also release a newer version of the module to the pypi with the changes in mind?

**Pull request merged**
