### PR TITLE
Document restart_delay & add start_delay as parameter instead of fixed value

### LINKED ISSUE #86: make open_url timeout configurable
Currently it is just set to 5, but I think it would make sense to make it configurable, using e.g. a open_url_timeout parameter.

If you think it is a good idea, should I suggest a pull request?

### PR DESCRIPTION
**Pull request by mgielda**
As in title - fixes #86 and adds doc to one parameter. I have put start_delay after restart_delay for compatibility, even though it would probably make sense to have those parameters the other way around.

### CODE REVIEW

**Comment by lepture** [comment]
@mgielda how about merge `start_delay` and `open_url` into `open_url_delay`. The default value is `None`, which means it won't open url.

**Comment by lepture** [comment]
ping @mgedmin

**Comment by lepture** [comment]
ping @mgielda

**Comment by mgielda** [comment]
Good suggestion @lepture - changed as suggested. The only problem is that livereload 2.4 stopped working for me (says ignoring introduction.rst and does not rebuild) so I reverted to 2.3.2 and have not been able to test this since.

**Comment by lepture** [comment]
@mgielda can you describe the problem in 2.4 in detail? I am going to make a release soon.

**Comment by lepture** [comment]
I've implemented the open_url_delay.

**Pull request closed without merging**
