### PR TITLE
use glob2 instead of stdlib glob to support recursive directories

### PR DESCRIPTION
**Pull request by struys**
It would be nice to use glob2 to support recursive file discovery - https://pypi.python.org/pypi/glob2

### CODE REVIEW

**Comment by struys** [comment]
bump. Any thoughts on this?

**Comment by dwt** [comment]
This would be really nice to document - like `formic`, which is sadly not python3 compatible. If I get this correctly though, glob2 does not have support for exclusions, which make it (sadly) a bit worse than formic for the task of concisely specifying which files to watch.

**Comment by lepture** [comment]
I think it would be good enough to document it on readme.

**Comment by AlJohri** [comment]
see #156

**Pull request closed without merging**
